In [4]:
import numpy as np
from numpy import*
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
np.array(range(10))
#[x for x in range(10)]これでも一緒。

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(start=5,step=5,stop=100,dtype="float")#np.arange(初項,等差,終点,変換)は等差数列を表わす。
#int:整数表示。float:浮動小数点。

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95.])

In [34]:
np.zeros(5,dtype="float")#array([ 0.,  0.,  0.,  0.,  0.])を生成。

array([ 0.,  0.,  0.,  0.,  0.])

In [35]:
for k in range(3):
    B=a[k]+b[k]
    print(B)

7
9
11


In [84]:
list= np.zeros(5,dtype="int")

a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
for k in range(5):
    list[k]=a[k]+b[k]#ristのk番目をa[k]+b[k]で置き換える。
print(list) 

[ 7  9 11 13 15]


In [100]:
list0=np.zeros(5,dtype="float")

a0=np.random.rand(5)#randomで0生成された0~1の間の数字で５つの要素の配列を生成。
b0=np.random.rand(5)

for k in range(5):
    list0[k]=a0[k]+b0[k]
print(list0) 

[ 1.2075248   0.94414099  1.42632402  0.87912285  1.23320702]


In [87]:
list1= np.array([0]*3,dtype="float")

a1=np.random.uniform(low=0,high=10,size=5)#randomで生成された0~10の間の数字で５つの要の配列を生成。小数あり
b1=np.random.randint(low=1,high=10,size=5)#randomで生成された0~10の間の数字で５つの要の配列を生成。整数
for k in range(3):
    list1[k]=a[k]+b[k]
print(list1) 

[ 1.15613064  0.65223801  0.94035535]


In [104]:
O = np.array([[0]*5 for k in range(5)],dtype='float')

a2=np.random.rand(5,5)
b2=np.random.uniform(0,10,(5,5))
c2=np.random.randint(1,10,(5,5))

for i in range(5):
        O[i,0] =a2[i,0]+b2[i,0]+c2[i,0]
        O[i,1] =a2[i,1]+b2[i,1]+c2[i,1]
        O[i,2] =a2[i,2]+b2[i,2]+c2[i,2]
        O[i,3] =a2[i,3]+b2[i,3]+c2[i,3]
        O[i,4] =a2[i,4]+b2[i,4]+c2[i,4]
print(O)

[[  9.31116274  10.1660041    5.73501753   9.16553413  12.48670964]
 [  2.74871624  12.74997085   9.4151196    9.12462219  13.22037729]
 [  1.70080565  14.33928402   5.03291398   2.17083927  10.25650206]
 [ 12.25160464   8.70554119  15.37066691  12.71382928  11.84087487]
 [  9.47536328  17.99868503   6.07379361  15.4538349   17.09405082]]


In [123]:
A = np.array([np.random.randint(10)for i in range(10)])
print(A)

res1 = np.array([0]*9,dtype='float')#9個の0で作られた配列を生成。[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
res2 = np.array([0]*8,dtype='float')

for i in range(0,len(A)-1):
    res1[i] =A[i+1]-A[i]#差分を表わしている（Δ）！！
print(res1)
    
B=np.diff(A)#上の式と一緒
C=np.diff(A,n=2)#2回差分
print(B)
print(C)

D=A[1:]-A[0:-1]
E=A[2:]-2*A[1:-1]+A[:-2]
print(D)
print(E)

[2 7 7 6 1 4 8 3 5 8]
[ 5.  0. -1. -5.  3.  4. -5.  2.  3.]
[ 5  0 -1 -5  3  4 -5  2  3]
[-5 -1 -4  8  1 -9  7  1]
[ 5  0 -1 -5  3  4 -5  2  3]
[-5 -1 -4  8  1 -9  7  1]


In [126]:
print(A)
print(A[1:])#一番左の項を消し、あらたな数列とする。
print(A[0:-1])#一番右の項を消し、新たな数列とする。

print(A[2:])#左2項を消し新たな数列とする。
print(A[1:-1])#一番左と右の項を消し、新たな数列とする。
print(A[:-2])#右から2項を消し、新たな数列とする。

[2 7 7 6 1 4 8 3 5 8]
[7 7 6 1 4 8 3 5 8]
[2 7 7 6 1 4 8 3 5]
[7 6 1 4 8 3 5 8]
[7 7 6 1 4 8 3 5]
[2 7 7 6 1 4 8 3]


参考URL：http://japanichaos.appspot.com/NumpyArray.html